---
- name: Install nginx
  apt:
    name: nginx
    state: present
  tags: nginx

- name: Enable nginx
  systemd:
    name: nginx
    enabled: yes
  tags: nginx

- name: Remove default nginx configuration
  file:
    name: '{{ item }}'
    state: absent
  loop:
    - /etc/nginx/sites-available/default
    - /etc/nginx/sites-enabled/default
  tags: nginx

- name: Copy wp config file
  template:
    src: server1.loc.conf.j2
    dest: /etc/nginx/sites-enabled/server1.loc.conf 
    mode: 0644
    owner: root
    group: root
  notify: Restart nginx
  tags: nginx

