---
- name: Update repo cache and upgrade all software
  apt:
    name: '*'
    state: latest
    update_cache: yes

- name: Install packages
  apt:
    name: '{{ item }}'
    state: present
  loop:
    - python3-pip
    - zip

- name: Install pymysql
  pip:
    name: pymysql
